//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pgc.EarlyBindings
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("pgc_PowerFxListFunctions")]
	public partial class pgc_PowerFxListFunctionsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Functions = "Functions";
			public const string Version = "Version";
		}
		
		public const string ActionLogicalName = "pgc_PowerFxListFunctions";
		
		public pgc_PowerFxListFunctionsResponse()
		{
		}
		
		public string[] Functions
		{
			get
			{
				if (this.Results.Contains("Functions"))
				{
					return ((string[])(this.Results["Functions"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Results["Functions"] = value;
			}
		}
		
		public string Version
		{
			get
			{
				if (this.Results.Contains("Version"))
				{
					return ((string)(this.Results["Version"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Version"] = value;
			}
		}
	}
}