//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pgc.EarlyBindings
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("pgc_PowerFxListFunctions")]
	public partial class pgc_PowerFxListFunctionsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "pgc_PowerFxListFunctions";
		
		public pgc_PowerFxListFunctionsRequest()
		{
			this.RequestName = "pgc_PowerFxListFunctions";
		}
	}
}