//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pgc.EarlyBindings
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("pgc_PowerFxEvaluate")]
	public partial class pgc_PowerFxEvaluateResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Output = "Output";
		}
		
		public const string ActionLogicalName = "pgc_PowerFxEvaluate";
		
		public pgc_PowerFxEvaluateResponse()
		{
		}
		
		public string Output
		{
			get
			{
				if (this.Results.Contains("Output"))
				{
					return ((string)(this.Results["Output"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Output"] = value;
			}
		}
	}
}