//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pgc.EarlyBindings
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("pgc_PowerFxEvaluate")]
	public partial class pgc_PowerFxEvaluateRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Context = "Context";
			public const string Yaml = "Yaml";
		}
		
		public const string ActionLogicalName = "pgc_PowerFxEvaluate";
		
		public string Context
		{
			get
			{
				if (this.Parameters.Contains("Context"))
				{
					return ((string)(this.Parameters["Context"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Context"] = value;
			}
		}
		
		public string Yaml
		{
			get
			{
				if (this.Parameters.Contains("Yaml"))
				{
					return ((string)(this.Parameters["Yaml"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Yaml"] = value;
			}
		}
		
		public pgc_PowerFxEvaluateRequest()
		{
			this.RequestName = "pgc_PowerFxEvaluate";
			this.Yaml = default(string);
		}
	}
}